env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
  sourceType: script
rules:
  no-inner-declarations: off
  no-unused-vars: off
  no-console: off
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - off
    - always

# {
#   "root": true,
#   "env": {
#     "browser": false,
#     "node": true,
#     "es6": true
#   },
#   "extends": ["eslint:recommended"],
#   "parserOptions": {
#     "ecmaVersion": 2017,
#     "sourceType": "script"
#   }
#   "rules": {
#     "no-unused-vars": ["warn", {"args": "none"}]
#   }
# }

# "array-bracket-spacing": ["warn", "never"],
# "arrow-body-style": ["warn", "as-needed"],
# "arrow-parens": ["warn", "as-needed"],
# "arrow-spacing": "warn",
# // "brace-style": "warn",
# "camelcase": "warn",
# "comma-spacing": ["warn", {"after": true}],
# "dot-notation": "warn",
# "indent": ["warn", 4, {
  # "SwitchCase": 1,
  # "FunctionDeclaration": {"parameters": 1},
  # "MemberExpression": 1,
  # "CallExpression": {"arguments": 1}
# }],
# "key-spacing": ["warn", {"beforeColon": false, "afterColon": true, "mode": "minimum"}],
# "keyword-spacing": "warn",
# "no-console": "off",
# "no-empty": "off",
# "no-multi-spaces": "warn",
# "no-redeclare": "off",
# "no-restricted-globals": ["warn", "Promise"],
# "no-trailing-spaces": "warn",
# "no-undef": "error",
# "padded-blocks": ["warn", "never"],
# "object-curly-spacing": ["warn", "never"],
# "quotes": ["warn", "single"],
# "react/prop-types": "off",
# "react/jsx-no-bind": "off",
# "semi": ["warn", "always"],
# "space-before-blocks": ["warn", "always"],
# "space-before-function-paren": ["warn", "never"],
# "space-in-parens": ["warn", "never"]
